name: steam
version: '218'
summary: Launcher for the Steam software distribution service
description: |
  Steam is a software distribution service with an online store, automated
  installation, automatic updates, achievements, SteamCloud synchronized
  savegame and screenshot functionality, and many social features.
adopt-info: steam
grade: stable
confinement: strict
base: core24
platforms:
  arm64:
    build-on: [arm64]
    build-for: [arm64]
compression: lzo
assumes:
  - snapd2.62

lint:
  # Snapcraft's `ldd` lint can't handle 32-bit things,
  # So just make it quiet and also make builds a surprising amount faster
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
  dot-local-share-steam:
    interface: personal-files
    read:
      - $HOME/.local/share/Steam
      - $HOME/Steam
    write:
      - $HOME/.local/share/Steam
      - $HOME/Steam
  dot-local-share-applications:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  dot-local-share-icons:
    interface: personal-files
    write:
      - $HOME/.local/share/icons
  user-fex-config:
    interface: personal-files
    read:
      - $HOME/snap/steam/common
      - $HOME/snap/steam/common/.fex-emu
      - $HOME/.fex-emu
      - $HOME/.config/proton-fixes
    write:
      - $HOME/snap/steam/common
      - $HOME/snap/steam/common/.fex-emu
      - $HOME/.fex-emu
      - $HOME/.config/proton-fixes
  desktop:
    mount-host-font-cache: false
  shmem:
    interface: shared-memory
    private: true

slots:
  steam:
    interface: dbus
    bus: session
    name: com.steampowered.PressureVessel.LaunchAlongsideSteam
  user-fex-config-slot:
    interface: content
    content: socket-directory
    write:
      - $HOME/snap/steam/common
      - $HOME/snap/steam/common/.fex-emu
      - $HOME/.fex-emu
      - $HOME/.config/proton-fixes

hooks:
  configure:
    plugs:
      - opengl

parts:
  gaming-graphics-core24:
    plugin: dump
    source: ./gaming-graphics-core24
  amd64-content:
    plugin: dump
    source: ./steam_218_amd64
  amd64-rootfs:
    plugin: dump
    source: ./amd64_rootfs
  fex-emu:
    plugin: dump
    source: ./fex-emu
  fex-emu-wine:
    plugin: dump
    source: ./fex-emu-wine
  fex-config:
    plugin: dump
    source: ./fex_config
  
apps:
  steam:
    command-chain: [bin/desktop-launch]
    command: usr/bin/fex_launcher.sh
    plugs:
      - shmem
      - desktop
      - desktop-legacy
      - wayland
      - home
      - x11
      - gsettings
      - hardware-observe
      - mount-observe
      - system-observe
      - network-observe
      - joystick
      - network
      - network-bind
      - opengl
      - audio-playback
      - audio-record
      - screen-inhibit-control
      - process-control
      - bluez
      - network-control
      - fuse-support
      - steam-support
      - removable-media
      - upower-observe
      - uinput
      - dot-local-share-steam
  report:
    command-chain: [bin/desktop-launch]
    command: usr/bin/FEXBash bin/steamreport
    environment:
      DISABLE_WAYLAND: 1
    plugs:
      - system-observe
      - hardware-observe
      - opengl
      - x11
      - desktop
  vulkaninfo:
    command-chain: [bin/desktop-launch]
    command: usr/bin/FEXBash bin/vulkaninfo
    plugs:
      - opengl
      - x11
      - desktop
  vkcube:
    command-chain: [bin/desktop-launch]
    command: usr/bin/FEXBash bin/vkcube
    plugs:
      - opengl
      - x11
      - desktop
  glxinfo:
    command-chain: [bin/desktop-launch]
    command: usr/bin/FEXBash bin/glxinfo
    plugs:
      - opengl
      - x11
      - desktop
  glxgears:
    command-chain: [bin/desktop-launch]
    command: usr/bin/FEXBash bin/glxgears
    plugs:
      - opengl
      - x11
      - desktop
  test:
    command-chain: [bin/desktop-launch]
    command: usr/bin/FEXBash tests/run.sh
    plugs:
      - opengl
      - x11
      - desktop
